# This defines the configuration of this application. Each defines a (sub) component that is loaded and
# used for this application. These components can provide specific functionality and define how different
# files in your app are loaded.

# This provides the HTTP REST interface for all exported resources
rest: true

# These reads GraphQL schemas to define the schema of database/tables/attributes.
graphqlSchema:  
  files: '*.graphql'

# Loads JavaScript modules such that their exports are exported as resources
jsResource: 
  files: resources.js 

# This loads files that define fastify routes using fastify's auto-loader
# fastifyRoutes: 
#   files: routes/*.cjs # specify the location of route definition modules
#   path: . # relative to the app-name, like  http://server/app-name/route-name

# This allows static files to be directly accessible
static: 
  files: 'dist/**'
  urlPath: 'app'